"""
Django settings for orderSystem project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0qh11qhiw(v5f_ux)#q7bez&ew9l#h^mg()_&+$5ri!c^t2di#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'www.apps.WwwConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "utils.md.AuthMiddlewarePathInfo",
    "utils.md.PermissionMiddleware",
]

ROOT_URLCONF = 'orderSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orderSystem.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




############
# SESSIONS #
############
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'



############
# 菜单相关   #
############
MENUS = {
    "ADMIN": {},
    "CUSTOMER": {},
}

############
# 项目配置   #
############
HOME_URL = "/home/"
NB_SESSION_KEY = "user_info"
NB_LOGIN_NAME = "login"

NB_WHITE_URL = ["/login/", "/sms/login/", '/send/sms/', "/v1/demo/", "/v2/demo/"]
NB_WHITE_PERMISSION_NAME = ["login", "sms_login", "send_sms", "v1_demo", "v2_demo"]
# NB_PERMISSIONS = {
#     "ADMIN": ["home", ],
#     "CUSTOMER": ['home', 'user'],
# }

NB_PERMISSIONS = {
    "ADMIN": {
        "logout": {"parent": None, "text": "退出"},    # 表示 "logout"是一级页面
        "home": {"parent": None, "text": "Profile Center"},

        # 梳理功能
        "level_list": {"parent": None, "text": "Level Management"}, # 一级页面
        "level_add": {"parent": "level_list", "text": "新建级别"}, # 二级页面
        "level_edit": {"parent": "level_list", "text": "修改级别"}, # 三级页面
        "level_delete": {"parent": "level_list", "text": "删除级别"},# 四级页面

        "price_list": {"parent": None, "text": "Price Policy"},
        "price_add": {"parent": "price_list", "text": "新建价格"},
        "price_edit": {"parent": "price_list", "text": "修改价格"},
        "price_delete": {"parent": "price_list", "text": "删除价格"},

        "customer_list": {"parent": None, "text": "Customer Management"},
        "customer_add": {"parent": "customer_list", "text": "新建客户"},
        "customer_edit": {"parent": "customer_list", "text": "编辑客户"},
        "customer_delete": {"parent": "customer_list", "text": "删除客户"},
        "customer_reset": {"parent": "customer_list", "text": "重置密码"},

        "record_list": {"parent": None, "text": "Transactions Management"},
        "record_add": {"parent": "record_list", "text": "新建交易"},

        # "user": {"parent": None, "text": "用户中心"},
        # "add_user": {"parent": "user", "text": "新建用户"},
        # "multi_import": {"parent": "add_user", "text": "批量导入"},
        # # "edit_user": {"parent": "user", "text": "编辑用户"},
        #
        # "level_list": {"parent": None, "text": "级别管理"},
        # "level_add": {"parent": "level_list", "text": "新建级别"},
        # "level_edit": {"parent": "level_list", "text": "修改级别"},
        # "level_delete": {"parent": "level_list", "text": "删除级别"},
        #
        # "price_list": {"parent": None, "text": "价格策略"},
        # "price_add": {"parent": "price_list", "text": "新建价格"},
        # "price_edit": {"parent": "price_list", "text": "修改价格"},
        # "price_delete": {"parent": "price_list", "text": "删除价格"},
        #
        # "price2_list": {"parent": None, "text": "价格策略2"},
        # "price2_add": {"parent": "price2_list", "text": "新建价格"},
        # "price2_edit": {"parent": "price2_list", "text": "修改价格"},
        # "price2_delete": {"parent": "price2_list", "text": "删除价格"},
        #
        # "level2_list": {"parent": None, "text": "级别管理2"},
        # "level2_add": {"parent": "level2_list", "text": "新建级别"},
        # "level2_edit": {"parent": "level2_list", "text": "修改级别"},
        # "level2_delete": {"parent": "level2_list", "text": "删除级别"},
        #
        # "customer2_list": {"parent": None, "text": "客户管理2"},
        #
        # "price3_list": {"parent": None, "text": "价格管理3"},
        # "price3_add": {"parent": "price3_list", "text": "新建级别"},
        # "price3_edit": {"parent": "price3_list", "text": "新建级别"},
        # "price3_delete": {"parent": "price3_list", "text": "新建级别"},
        # "price3_export": {"parent": "price3_list", "text": "新建级别"},
        #
        # "level3_list": {"parent": None, "text": "级别管理3"},
        # "level3_add": {"parent": "price3_list", "text": "新建级别"},
        # "level3_edit": {"parent": "price3_list", "text": "编辑别"},
        # "level3_delete": {"parent": "price3_list", "text": "删除级别"},
        #
        # "customer_list": {"parent": None, "text": "客户管理"},
        # "customer_add": {"parent": "customer_list", "text": "新建客户"},
        # "customer_edit": {"parent": "customer_list", "text": "编辑客户"},
        # "customer_delete": {"parent": "customer_list", "text": "删除客户"},
        # "customer_reset": {"parent": "customer_list", "text": "重置密码"},
        #
        # "level4_list": {"parent": None, "text": "级别管理4"},
        # "level4_add": {"parent": "price3_list", "text": "新建级别"},
        # "level4_edit": {"parent": "price3_list", "text": "编辑别"},
        # "level4_delete": {"parent": "price3_list", "text": "删除级别"},
        #
        # "price4_list": {"parent": None, "text": "级别管理4"},
        # "price4_add": {"parent": "price3_list", "text": "新建级别"},
        # "price4_edit": {"parent": "price3_list", "text": "编辑别"},
        # "price4_delete": {"parent": "price3_list", "text": "删除级别"},
        #
        # "customer4_list": {"parent": None, "text": "客户管理4"},
        # "customer4_add": {"parent": "customer_list", "text": "新建客户"},
        # "customer4_edit": {"parent": "customer_list", "text": "编辑客户"},
        # "customer4_delete": {"parent": "customer_list", "text": "删除客户"},
        # "customer4_reset": {"parent": "customer_list", "text": "重置密码"},
        #
        # "v3_list": {"parent": None, "text": "客户管理4"},
        # "v3_add": {"parent": "v3_list", "text": "新建客户"},
        # "v3_edit": {"parent": "v3_list", "text": "编辑客户"},
        # "v3_delete": {"parent": "v3_list", "text": "删除客户"},
        # "v3_reset": {"parent": "v3_list", "text": "重置密码"},
        #
        # "depart_list": {"parent": None, "text": "客户管理4"},
        # "depart_add": {"parent": "depart_list", "text": "新建客户"},
        # "depart_edit": {"parent": "depart_list", "text": "编辑客户"},
        # "depart_delete": {"parent": "depart_list", "text": "删除客户"},
        #
        # "info_list": {"parent": None, "text": "客户管理4"},
        # "info_add": {"parent": "info_list", "text": "新建客户"},
        # "info_edit": {"parent": "info_list", "text": "编辑客户"},
        # "info_delete": {"parent": "info_list", "text": "删除客户"},

    },
    "CUSTOMER": {
        "logout": {"parent": None, "text": "退出"},
        "home": {"parent": None, "text": "Profile Center"},

        "info_list": {"parent": None, "text": "用户资料"},
        "info2_list": {"parent": None, "text": "用户资料2"},

        "mine_tran": {"parent": None, "text": "我的交易记录"},
        "tran2_list": {"parent": None, "text": "我的交易记录2"},

        "yang_list": {"parent": None, "text": "x视频"},
        "yang_add": {"parent": "yang_list", "text": "下单"},
        "yang_cancel": {"parent": "yang_list", "text": "撤单"},

        "yang2_list": {"parent": None, "text": "x视频2"},
        "yang2_add": {"parent": "yang2_list", "text": "下单2"},
        "yang2_cancel": {"parent": "yang2_list", "text": "撤单2"},
    },
}

NB_MENUS = {
    "ADMIN": [
        {
            "text": "Configuration",
            'icon': "fa-bank",
            "children": [
                {"text": "Level Management", "name": "level_list", "url": "/level/list/"},
                {"text": "Price Policy", "name": "price_list", "url": "/price/list/"},
            ]
        },
        {
            "text": "Order",
            'icon': "fa-bank",
            "children": [
                {"text": "Customer Management", "name": "customer_list", "url": "/customer/list/"},
                {"text": "Transactions Management", "name": "record_list", "url": "/record/list/"},
            ]
        },
    ],
    "CUSTOMER": [
        {
            "text": "用户信息",
            'icon': "fa-bed",
            "children": [
                {"text": "个人资料", "name": "info", "url": "/info/list/"},
                {"text": "个人资料2", "name": "info2_list", "url": "/info2/list/"},
                {"text": "我的交易记录", "name": "mine_tran", "url": "/mine/tran/"},
                {"text": "我的交易记录2", "name": "tran2_list", "url": "/tran2/list/"},
            ]
        },
        {
            "text": "平台分类",
            'icon': "fa-bed",
            "children": [
                {"text": "x视频", "name": "yang_list", "url": "/yang/list/"},
                {"text": "x视频2", "name": "yang2_list", "url": "/yang2/list/"},
            ]
        },
    ]
}
# MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
# MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MESSAGE_DANDER_TAG = 50
MESSAGE_TAGS = {
    MESSAGE_DANDER_TAG: "danger",
}
# MESSAGE_LEVEL = 20

try:
    from .local_settsing import *
except ImportError:
    pass
