# Generated by Django 3.2 on 2024-02-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待执行'), (2, '正在执行'), (3, '已完成'), (4, '失败')], default=1, verbose_name='状态'),
        ),
    ]
