# Generated by Django 3.2 on 2024-02-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20240217_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='percent',
            field=models.IntegerField(help_text='填入0-100整数表示百分比，例如：90，表示90%', verbose_name='折扣'),
        ),
    ]
