# Generated by Django 3.2 on 2024-02-19 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_level_percent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='TransactionRecord',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', '手机号格式错误')], verbose_name='手机号'),
        ),
    ]
